//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsoSoftLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AsoSoftLibrary.resFiles", typeof(resFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G,P,Desc
        ///ڴ,ĝ,Garusi Consonant
        ///ڎ,đ,Hewrami Consonant
        ///ۉ,ŵ,Hewrami Consonant
        ///ݵ,ė,Hewrami Vowel
        ///ݸ,ȯ,Hewrami Vowel
        ///ۊ,ẅ,Southern Vowel
        ///ئ,ʔ,
        ///ب,b,
        ///پ,p,
        ///ت,t,
        ///ج,c,
        ///چ,ç,
        ///ح,ḧ,
        ///خ,x,
        ///د,d,
        ///ر,r,
        ///ڕ,ř,
        ///ز,z,
        ///ژ,j,
        ///س,s,
        ///ش,ş,
        ///ع,ƹ,
        ///غ,ẍ,
        ///ف,f,
        ///ڤ,v,
        ///ق,q,
        ///ک,k,
        ///گ,g,
        ///ل,l,
        ///ڵ,ł,
        ///م,m,
        ///ن,n,
        ///ه,h,
        ///ا,a,
        ///ۆ,o,
        ///ە,e,
        ///ێ,ê,
        ///^ی,y,
        ///^و,w,
        ///(?&lt;=[aeêo])و,w,after vowel
        ///و(?=[aeêo]),w,before vowel
        ///(?&lt;=[aeêo])ی,y,after vowel
        ///ی(?=[aeêo]),y,before vowel
        ///^([bçdjl])$,$1i,چ=&gt;çi bcçdfghḧjklłmnpqrřsştvwxẍyzʔƹ.
        /// </summary>
        public static string G2PCertain {
            get {
                return ResourceManager.GetString("G2PCertain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphemes,Phonems
        ///حەییی,ḧeyyî
        ///تەییی,teyyî
        ///ئاگر,ʔagir
        ///قانع,qaniƹ
        ///سالم,salim
        ///عاشق,ƹaşiq.
        /// </summary>
        public static string G2PExceptions {
            get {
                return ResourceManager.GetString("G2PExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From,To,Desc
        ///00AC,200C,Wrong ZWNJ by MS Word
        ///066A,0025,Arabic PERCENT SIGN
        ///066B,002E,Arabic DECIMAL SEPARATOR
        ///066C,002C,Arabic THOUSANDS SEPARATOR
        ///066D,002A,Arabic FIVE POINTED STAR
        ///0751,062B,ݑ
        ///0752,067E,ݒ
        ///0750,067E,ݐ
        ///0753,062A,ݓ
        ///067F,062A,ٿ
        ///0679,062A,ٹ
        ///0758,0686,ݘ
        ///0689,062F,ډ
        ///068A,062F,ڊ
        ///068B,062F,ڋ
        ///068C,062F,ڌ
        ///068D,062F,ڍ
        ///068F,062F,ڏ
        ///0690,062F,ڐ
        ///0759,062F,ݙ
        ///075A,062F,ݚ
        ///076C,0695,ݬ
        ///0691,0695,ڑ
        ///0692,0695,ڒ
        ///0693,0695,ړ
        ///0694,0695,ڔ
        ///0696,0695,ږ
        ///0697,0698,ڗ
        ///0699,0698,ڙ
        ///076B,0698,ݫ
        ///069A,0633,ښ
        ///069B,0633,ڛ
        ///069C,0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NormalizerAdditional {
            get {
                return ResourceManager.GetString("NormalizerAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From,To,Desc
        ///A78C,0027,Latin Small Letter Saltillo ꞌ
        ///FEFF,200C,ZERO WIDTH NO-BREAK SPACE
        ///200B,200C,ZERO WIDTH SPACE
        ///2010,002D,HYPHEN
        ///2011,002D,NON-BREAKING HYPHEN
        ///2012,002D,FIGURE DASH
        ///2013,002D,EN DASH
        ///2014,002D,EM DASH
        ///2015,002D,HORIZONTAL BAR
        ///2212,002D,Minus
        ///00AD,002D,Soft Hyphen
        ///FE58,002D,SMALL EM DASH
        ///FE63,002D,MALL HYPHEN-MINUS
        ///FF0D,002D,FULLWIDTH HYPHEN-MINUS
        ///1680,0020,OGHAM SPACE MARK
        ///2000,0020,EN QUAD
        ///2001,0020,EM QUAD
        ///2002,0020,EN SPACE
        ///2003,0020,EM SPACE
        ///2004,0020,THREE-PER-EM SPACE
        ///2005,0020,FOU [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NormalizerDeep {
            get {
                return ResourceManager.GetString("NormalizerDeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phoneme,ASCII
        ///ʔ,EH
        ///a,AA
        ///b,B
        ///p,P
        ///t,T
        ///c,JE
        ///ç,CH
        ///ḧ,HE
        ///x,X
        ///d,D
        ///r,R
        ///ř,RR
        ///z,Z
        ///j,ZH
        ///s,S
        ///ş,SH
        ///ƹ,AH
        ///ẍ,XE
        ///f,F
        ///v,V
        ///q,Q
        ///k,K
        ///g,G
        ///l,L
        ///ł,LL
        ///m,M
        ///n,N
        ///o,O
        ///e,A
        ///h,H
        ///ê,E
        ///î,I
        ///y,Y
        ///w,W
        ///u,U
        ///û,UU.
        /// </summary>
        public static string Phoneme2Ascii {
            get {
                return ResourceManager.GetString("Phoneme2Ascii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phoneme,IPA
        ///ng,ŋg
        ///ʔ,ʔ
        ///b,b
        ///p,p
        ///t,t
        ///c,d͡ʒ
        ///ç,t͡ʃ
        ///ḧ,ħ
        ///x,x
        ///d,d
        ///r,ɾ
        ///ř,r
        ///z,z
        ///j,ʒ
        ///s,s
        ///ş,ʃ
        ///ƹ,ʕ
        ///ẍ,ɣ
        ///f,f
        ///v,v
        ///q,q
        ///k,k
        ///g,g
        ///l,l
        ///ł,ɫ
        ///m,m
        ///n,n
        ///w,w
        ///u,ʊ
        ///û,u
        ///o,o̞
        ///h,h
        ///y,j
        ///a,ä
        ///e,a
        ///ê,ɛ
        ///i,ɪ
        ///î,i
        ///ĝ,ŋ
        ///đ,đ
        ///ü,y
        ///ô,ô
        ///õ,õ.
        /// </summary>
        public static string Phoneme2IPA {
            get {
                return ResourceManager.GetString("Phoneme2IPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency,WeightPattern,Title
        ///1044,–∪–––∪–––∪–––∪–,فاعلاتن فاعلاتن فاعلاتن فاعلن
        ///999,∪–––∪–––∪–––∪–––,مفاعیلن مفاعیلن مفاعیلن مفاعیلن
        ///386,∪–––∪–––∪––,مفاعیلن مفاعیلن فعولن
        ///334,––∪∪––∪∪––∪∪––,مفعولُ مفاعیلُ مفاعیلُ فعولن
        ///272,––∪∪––∪∪––∪∪–,مفعولُ مفاعیلُ مفاعیلُ فعل
        ///213,––∪–∪–∪∪––∪–∪–,مفعولُ فاعلاتُ مفاعیلُ فاعلن
        ///138,∪∪––∪∪––∪∪––∪∪–,فعلاتن فعلاتن فعلاتن فعلن
        ///131,––∪∪–∪–∪––,مفعولُ مفاعلن فعولن
        ///62,–∪–––∪–––∪–,فاعلاتن فاعلاتن فاعلن
        ///45,∪∪––∪–∪–∪∪–,فعلاتن مفاعلن فعلن
        ///40,∪–∪–∪∪––∪–∪–∪∪–,مفاعلن فعلاتن مفاعلن فعلن
        ///31 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PoemPatterns {
            get {
                return ResourceManager.GetString("PoemPatterns", resourceCulture);
            }
        }
    }
}
